module.exports = {
  "intro-exercises": "1-Introduction",
  "agents-exercises": "2-Intelligent-Agent",
  "search-exercises": "3-Solving-Problems-By-Searching",
  "advanced-search-exercises": "4-Beyond-Classical-Search",
  "game-playing-exercises": "5-Adversarial-Search",
  "csp-exercises": "6-Constraint-Satisfaction-Problems",
  "knowledge-logic-exercises": "7-Logical-Agents",
  "fol-exercises": "8-First-Order-Logic",
  "logical-inference-exercises": "9-Inference-In-First-Order-Logic",
  "planning-exercises": "10-Classical-Planning",
  "advanced-planning-exercises": "11-Planning-And-Acting-In-The-Real-World",
  "kr-exercises": "12-Knowledge-Representation",
  "probability-exercises": "13-Quantifying-Uncertainity",
  "bayes-nets-exercises": "14-Probabilistic-Reasoning",
  "dbn-exercises": "15-Probabilistic-Reasoning-Over-Time",
  "decision-theory-exercises": "16-Making-Simple-Decisions",
  "complex-decisions-exercises": "17-Making-Complex-Decision",
  "concept-learning-exercises": "18-Learning-From-Examples",
  "ilp-exercises": "19-Knowledge-In-Learning",
  "bayesian-learning-exercises": "20-Learning-Probabilistic-Models",
  "reinforcement-learning-exercises": "21-Reinforcement-Learning",
  "nlp-communicating-exercises": "22-Natural-Language-Processing",
  "nlp-english-exercises": "23-Natural-Language-For-Communication",
  "perception-exercises": "24-Perception",
  "robotics-exercises": "25-Robotics",
  "philosophy-exercises": "26-Philosophical-Foundations",
  "future-exercises": "Future Exercises"
}